name: annotations_cheat_sheet
description: A Dart annotations cheat sheet
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  dart_code_metrics_annotations: ^1.1.0
  dart_code_metrics_presets: ^2.25.1
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
